Hackathon2018/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sleepez.urls', namespace='sleepez')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sleepez/urls.py
from sleepez import views
from django.conf.urls import url

appname = 'sleepez'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^about/$', views.about, name='about'),
    url(r'^google_maps/$', views.google_maps, name='google_maps'),
    url(r'^update/', views.update, name='update'),
    url(r'^directions/(?P<origin>\w+)-(?P<destination>[\w|\W]+)/$', views.directions, name='directions'),
    url(r'^form/', views.search_form , name='update'),
    url(r'^host_form/', views.HostCreateView.as_view(), name="host_form"),
]

sleepez/models.py
from django.db import models


# Create your models here.
class Shelter(models.Model):
    name = models.CharField(max_length=45, blank=False)
    address = models.CharField(max_length=200, blank=False)
    phone = models.CharField(max_length=45, blank=True)
    post_code = models.CharField(max_length=5, blank=True)
    latitude = models.CharField(max_length=20, blank=False)
    longitude = models.CharField(max_length=20, blank=False)
    borough = models.CharField(max_length=45)


class PotentialHost(models.Model):
    name = models.CharField(max_length=45, blank=False)
    address = models.CharField(max_length=200, blank=False)
    borough = models.CharField(max_length=45)
    contact_name = models.CharField(max_length=45)
    contact_phone = models.CharField(max_length=45, blank=False)
    contact_email = models.CharField(max_length=45, blank=True)

sleepez/forms.py
from django import forms
from .models import PotentialHost


class SearchForm(forms.Form):
    address = forms. CharField(
        max_length=200,
        label='Enter your address:',
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'id': 'pac-input',
                'placeholder': '55 Lexington Avenue, New York NY'
            }
        )
    )

#
# class HostForm(forms.Form):
#     name = forms.CharField(
#         max_length=45,
#         label = 'Organization name:',
#         widget=forms.TextInput()
#     )


class HostForm(forms.ModelForm):
    class Meta:
        model = PotentialHost
        fields = '__all__'
        # fields =['name']
        widgets = {
            forms.TextInput(attrs={
                'class': 'form-control',
            })
        }


class SearchForm(forms.Form):
    address = forms. CharField(
        max_length=200,
        label='Enter your address:',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'address-input',
                'placeholder': '55 Lexington Avenue, New York NY'
            }
        )
)


# class AddressForm(forms.ModelForm):
#     class Meta:
#         model = Address
#         fields = ('address',)
#
#

sleepez/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from .templatetags.shelter_tags import *
from django.conf import settings
from .forms import SearchForm
from .models import PotentialHost
# from .models import Shelter
from .utils import update_shelters


# Create your views here.
def index(request):
    return render(request, 'sleepez/index.html')


def about(request):
    return render(request, 'sleepez/about.html')    


def sign_up(request):
    return render(request, 'sleepez/sign_up.html')


def update(request):
    update_shelters()
    return HttpResponse('Shelters have been updated.')


def google_maps(request):
    return render(request, 'sleepez/google_maps.html', {
        'shelters': Shelter.objects.all()
    })


def directions(request, origin, destination):
    # destination = shelter.address
    destination = destination
    url = ('https://www.google.com/maps/embed/v1/directions?' +
           'key='+settings.MAPS_API_KEY +
           '&origin='+origin +
           '&destination=' + destination +
           '&mode=walking&zoom=15'
           )
    context_dict = {
        'url': url,
        'origin': origin,
        'destination': destination,
    }
    return render(request, 'sleepez/search.html', context_dict)


def search_form(request):
    form = SearchForm
    context_dict = {'address_validator': form}
    return render(request,'sleepez/search_form.html', context_dict)


class HostCreateView(SuccessMessageMixin, CreateView):
    model = PotentialHost
    fields = '__all__'
    template_name = 'sleepez/host_form.html'
    success_message = 'Application has been processed. Allow a couple of days for us to review it.'
    success_url = '#'

sleepez/templates/sleepez/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h1 id="title">Collaborators</h1>
      <div class="card-group">
    <!-- ALEX F-V  -->
      <div class="card about bg-dark">
        <img class="card-img-top" src="{% static 'img/profile_alex.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Alex Flores-Veliz</h5>
          <p class="card-text">Alex is a Junior at Lehman College studying Computer Science. He enjoys yelling at his tv while watching football and practicing his hobby of graphic design as often as he can.</p>
        </div>
        <div class="card-footer">
          <i class="fab fa-github-alt fa-lg"><a class="github-link" target="_blank" href="https://github.com/AlexFloresVeliz"> Github</a></i>
        </div>
      </div>
    <!-- Jordan Falcon  -->
      <div class="card bg-dark">
        <img class="card-img-top" src="{% static 'img/jordan_falcon_profile_pic.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Jordan Falcon</h5>
          <p class="card-text">Jordan is currently a Computer Science student at Lehman College aspiring to a be a professional web developer.He strongly believes that Lebron James is the GOAT.</p>
        </div>
        <div class="card-footer">
          <i class="fab fa-github-alt fa-lg"><a class="github-link" target="_blank" href="https://github.com/j-falcon122"> Github</a></i>
        </div>
      </div>
    <!-- Harold De Leon  -->
      <div class="card bg-dark">
        <img class="card-img-top" src="{% static 'img/profile_default.png' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Harold De Leon</h5>
          <p class="card-text">Harold is a Junior at Lehman College studying Computer Science.</p>
        </div>
        <div class="card-footer">
          <i class="fab fa-github-alt fa-lg"><a class="github-link" target="_blank" href="https://github.com/HaroldDLeon"> Github</a></i>
        </div>
      </div>
    </div>
    <!-- GROUP 2 -->
    <div class="card-group">
    <!-- Amado Suarez -->
      <div class="card bg-dark">
        <img class="card-img-top" src="{% static 'img/amado_profile.jpeg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Amado Suarez</h5>
          <p class="card-text">Amado is a passionate Junior working towards a B.S. degree in Computer Science at Lehman College. Strong interest in technology, software development, data science, and how these can be used to improve the world we live in.</p>
        </div>
        <div class="card-footer">
          <i class="fab fa-github-alt fa-lg"><a class="github-link" target="_blank" href="https://github.com/AmadoSuarez"> Github</a></i>
        </div>
      </div>
    <!-- Isaac Atif  -->
      <div class="card bg-dark">
        <img class="card-img-top" src="{% static 'img/isaac_profile.jpeg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Isaac Atif</h5>
          <p class="card-text">Isaac is a Junior at Lehman College studying Computer Science.</p>
        </div>
        <div class="card-footer">
          <i class="fab fa-github-alt fa-lg"><a class="github-link" target="_blank" href="https://github.com/Isaaclipse"> Github</a></i>
        </div>
      </div>
    </div>
</div>
</div>
</div>
{% endblock %}

sleepez/templates/sleepez/google_maps.html
{% extends 'base.html'  %}
{% load static %}
{% block title %}
    <title> Google Maps Demo</title>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAso1CPfl8yBx56oJI7wVUE0yJL3o_bx0k&callback=getLocation">
    </script>
    <script>
        console.log("loading...");
        var lat = 40.7408092;
        var long = -73.98265169999999;
        var shelter_locations = [];

        function refresh() {
          // TODO - Add functionality when map does not load.
          // $('body').load("ajax/google_maps.html");
        }
        
        function getLocation() {
          if (navigator.geolocation) {

            // TODO - fix real time geolocations, the line below currently works BUT slow
            // navigator.geolocation.getCurrentPosition(setPosition, error, options)

            initMap(lat, long)  //*For Demo* fixed coordinates to Baruch College

          } 
          else {
              $demo.html("Geolocation is not supported by this browser.");
          }

        }

        var options = {
          enableHighAccuracy: true,
          timeout: 30000,
          maximumAge: 0
        };

        function error(err) {
          console.warn(`ERROR(${err.code}): ${err.message}`);
        }

        function setPosition(position){
          lat = position.coords.latitude;
          long = position.coords.longitude;
          initMap(lat, long)
        }

        function initMap(lat, long) {
          var uluru = {lat: lat, lng: long};
          var image = {
            url: "{% static  'img/pointer.png' %}",
          };

          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: uluru
          });

          var marker = new google.maps.Marker({
            position: uluru,
            map: map,
            draggable:true,
          });

          shelter_locations = getShelterLocations();
          for (var i = 0; i < shelter_locations.length; i++) {
            var shelter_location = shelter_locations[i];
            var marker = new google.maps.Marker({
              position: {lat: shelter_location[1], lng: shelter_location[2]},
              map: map,
              icon: image,
              title: shelter_location[0]
            });
          }

        }

        function getShelterLocations() {
          console.log("get here???");
            {% for shelter in shelters %}
                shelter_locations.push(['{{shelter.name}}', parseFloat('{{shelter.latitude}}'), parseFloat('{{shelter.longitude}}') ]);
            {% endfor%}
            console.log(shelter_locations);
            return shelter_locations;
          }
      </script>
{% endblock %}
{% block content %}
<div class="container">
    <div id="map"></div>
    <!-- <button onclick="refresh()">Reload</button> -->
    <p id="demo" style="visibility: hidden">demo</p>
</div>
<div class="container">
    <h3>List of institutions:</h3>
    <div class="list-group">
        {% for item in shelters %}
            <a href="{% url 'sleepez:directions' origin='sas' destination=item.name %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1" style="color:black">{{item.name}}</h5>
        </div>
        <p class="mb-1" style="color:black">Address: {{item.address}}
            <br/>       Phone Number: {{item.phone}}
        </p>
        </a>
        {% endfor %}
    </div>
    
</div>
{% endblock %}

sleepez/templates/sleepez/host_form.html
{% extends 'base.html' %}
{% block content %}
{% load shelter_tags %}
    <div class="container card">
        <div class="card-body">
            <h2>Apply to become a Host Organization.</h2>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label }}
                    {{ field|add_class:'form-control' }}
                {% endfor %}
                <br/>
                <button class="btn btn-primary" type="submit">Submit application</button>
            </form>
        </div>
    </div>
{% endblock %}

sleepez/templates/sleepez/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- CAROUSEL -->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'img/slide2.jpg' %}" alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Let's help the less fortunate have a goodnights sleep</h5>
            <p>We as humans have an obligation to help those around us. With tech becoming more accesable, we shouldn't forget those that are still held back.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/slide4.jpg' %}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
              <h5>The less fortunate need our help even more than ever</h5>
              <p>In recent years, homelessness in New York City has reached the highest levels since the Great Depression of the 1930s.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/slide1.jpg' %}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
              <h5>SleepEZ - Helping the homeless find a goodnights sleep</h5>
              <p>With SleepEZ, we plan on using the LinkNYC kiosks to help the homeless find that goodnights sleep everyone deserves.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <!-- /CAROUSEL -->
    <div class="container">
    <h1 id="title">SleepEZ</h1>
      <p class="page-text">In a city that houses 63,343 homeless people in the municipal shelter system, we need to come up with improved ways of sharing information on available spaces for the needy to sleep during the night, especially those with no direct access to the internet. So how do the homeless, a user base that more likely than not can’t afford a cell phone with internet capabilities, find a shelter to stay the night in? They find it, with SleepEZ.</p>
      <p class="page-text">SleepEZ, designed to help those without access to the internet, is an app found on the ever emerging LinkNYC kiosks found around NYC. The app is created to fetch a users location and point them to the nearest shelter location in their area. The kiosks would also show the number of available beds within a 3 mile radius in a advertisement style ad, like the ones the LinkNYC kiosks already show users.</p>

      <a href="http://localhost:8000/google_maps/" class="index-sleepez-button btn btn-primary">Try SleepEZ today!</a>
      <br>

      <div class="row">

        <div class="col-sm-6">
          <div class="card border-info bg-dark">
            <img class="card-img-top" src="{% static 'img/linknyc.png' %}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">LinkNYC</h5>
              <p class="card-text">Founded in 2014, LinkNYC provides superfast, free public Wi-Fi, phone calls, device charging and a tablet for access to city services, maps and directions. We think there is much more we can do with these Links.</p>
              <a href="https://www.link.nyc/" class="btn btn-primary">Learn More About LinkNYC</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card border-info bg-dark">
            <img class="card-img-top" src="{% static 'img/linknyc2_site.png' %}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Using LinkNYC for more than WIFI</h5>
              <p class="card-text">LinkNYC is useful for more than just free high speed Wifi and advertisements on prime time television shows. Click on the button below for more information on what features and services you can get at your local LinkNYC!</p>
              <a href="https://www.link.nyc/assets/downloads/LinkNYC-Fact-Sheet.pdf" class="btn btn-primary">LinkNYC Features</a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

sleepez/templates/sleepez/search.html
{% extends 'base.html'   %}
{% block title %}
    <title>Directions from {{origin}} to {{destination}}</title>
{% endblock %}
{% block content %}
    <div class="container">
        <iframe onload="this.width=screen.width*0.6; this.height=screen.height*0.5;" frameborder="0" style="border:0"
            src="{{ url }}" allowfullscreen>
        </iframe>
    </div>
{% endblock %}

sleepez/templates/sleepez/search_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'address_validator.html' %}
{% endblock %}

templates/address_validator.html
<script>
    function initAutocomplete() {
        // Create the search box and link it to the UI element.
        var input = document.getElementById('address-input');
        var searchBox = new google.maps.places.SearchBox(input);
    }
</script>
    <div class="container">
        {{ address_validator.as_p }}
        <script src="https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete" async defer></script>
    </div>

templates/base.html
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block title %}
      <title>SleepEZ</title>
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" style="font-size: 2em;" href="/google_maps">
      <img src="{% static 'img/sleepez-v2.svg' %}" width="50" height="50" class="d-inline-block" alt="lol">
      SleepEZ
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'sleepez:index' %}">Home <span class="sr-only"></span></a>
          <a class="nav-item nav-link" href="#">Resource Locations</a>
          <a class="nav-item nav-link" href="/google_maps">Locate</a>
          <a class="nav-item nav-link" href="{% url 'sleepez:about' %}">About Us</a>
        </div>
      </div>
    </nav>
      {% include 'messages.html' %}
      {% block content %}
      {% endblock %}
          <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!--Footer-->
    <footer class="page-footer font-small bg-dark pt-4 mt-4">
        <!--Footer Links-->
        <div class="container text-center text-md-left">
            <div class="row">
                <!--First column-->
                <div class="col-md-4">
                  <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Let's help our community SleepEZ</h5>
                  <p id="footer-text">If you are an institution willing to open your doors for the night so that the less fortunate may have a place to rest their head, please sign up for our service with the link below.</p>
                </div>
                <!--/.First column-->
                <hr class="clearfix w-100 d-md-none">
                <!--Fourth column-->
                <div class="col-md-3 mx-auto">
                    <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Contact Us</h5>
                    <ul class="list-unstyled">
                        <li class="contact">
                          <p>
                          <i class="fas fa-home"></i> Bronx, NY, 10460, US
                          </p>
                        </li>
                        <li class="contact">
                          <p>
                          <i class="far fa-envelope"></i> contact@sleepez.io
                          </p>
                        </li>
                        <li class="contact">
                          <p>
                          <i class="fas fa-phone"></i> +01 718 656 8768
                          </p>
                        </li>
                        <!-- <li class="contact">
                          <p>
                          <i class="fas fa-home"></i> Bronx, NY, 10460, US
                          </p>
                        </li> -->
                    </ul>
                </div>
                <!--/.Fourth column-->
            </div>
        </div>
        <!--/.Footer Links-->
        <hr>
        <!--Call to action-->
        <div class="text-center py-3">
            <ul class="list-unstyled list-inline mb-0">
                <li class="list-inline-item">
                    <h5 class="mb-1">Register for free</h5>
                </li>
                <li class="list-inline-item">
                    <a href="{% url 'sleepez:sign_up' %}" class="btn btn-danger btn-rounded">Sign up!</a>
                </li>
            </ul>
        </div>
        <!--/.Call to action-->
        <hr>
        <!--Social buttons-->
        <div class="text-center">
            <ul class="list-unstyled list-inline">
                <li class="list-inline-item">
                    <a href="#" class="btn-floating mx-1">
                        <i class="fab fa-facebook fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn-floating mx-1">
                        <i class="fab fa-twitter fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://github.com/j-falcon122/CUNY-Hackathon-2018" target="_blank" class="btn-floating mx-1">
                        <i class="fab fa-github-alt fa-2x"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn-floating mx-1">
                        <i class="fab fa-linkedin fa-2x"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn-floating mx-1">
                        <i class="fab fa-instagram fa-2x"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!--/.Social buttons-->
        <!--Copyright-->
        <div class="footer-copyright py-3 text-center">
            © 2018 Copyright
        </div>
        <!--/.Copyright-->
    </footer>
    <!--/.Footer-->
    </body>
</html>

templates/messages.html
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{%  if message.tags %}{{ message.tags }}{% endif %}" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}